sudo: required
dist: trusty
git:
  depth: 1
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
install:
  - npm install
script:
  - npm test 
after_success:
  - npm run coverage 
  - npm run release
