sudo: required
dist: focal
git:
  depth: 1
language: node_js
node_js:
  - lts/* 
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
install:
  - yarn 
script:
  - yarn ci 
after_success:
  - yarn ci:afterSuccess 
