import { ApplicationIdentifier } from './application-identifier';
import { AICode } from '../enums';

const data = [
  {
    code: AICode.SerialShippingContainerCode,
    description: 'Serial Shipping Container Code',
    length: 18,
    variableLength: false,
  },
  {
    code: AICode.GTIN,
    description: 'Global Trade Item Number',
    length: 14,
    variableLength: false,
  },
  {
    code: AICode.GTINContainer,
    description: 'GTIN of Contained Trade Items',
    length: 14,
    variableLength: false,
  },
  {
    code: AICode.BatchLot,
    description: 'Batch/Lot Number',
    length: 20,
    variableLength: true,
  },
  {
    code: AICode.ProductionDate,
    description: 'Production Date',
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.DueDate,
    description: 'DueDate',
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.PackagingDate,
    description: 'Packaging Date',
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.BestBeforeDate,
    description: 'Best Before Date YYMMDD',
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ExpirationDate,
    description: 'Expiration Date',
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductVariant,
    description: 'Product Variant',
    length: 2,
    variableLength: false,
  },
  {
    code: AICode.SerialNumber,
    description: 'Serial Number',
    length: 20,
    variableLength: true,
  },
  {
    code: AICode.SecondaryDataFields,
    description: 'Secondary Data Fields',
    length: 29,
    variableLength: true,
  },
  {
    code: AICode.LotnumberN,
    description: 'Lot number[n]',
    length: 19,
    variableLength: true,
  },
  {
    code: AICode.AdditionalProductIdentification,
    description: 'Additional Product Identification',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.CustomerPartNumber,
    description: 'Customer Part Number',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.MadeToOrderVariationNumber,
    description: 'Made-to-Order Variation Number',
    length: 6,
    variableLength: true,
  },
  {
    code: AICode.SecondarySerialNumber,
    description: 'Secondary Serial Number',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.ReferencetoSourceEntity,
    description: 'Reference to SourceEntity',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.GlobalDocumentTypeIdentifier,
    description: 'Global Document Type Identifier',
    length: 17,
    variableLength: true,
  },
  {
    code: AICode.GLNExtensionComponent,
    description: 'GLN Extension Component',
    length: 20,
    variableLength: true,
  },
  {
    code: AICode.GlobalCouponNumberGCN,
    description: 'Global Coupon Number GCN',
    length: 25,
    variableLength: true,
  },
  {
    code: AICode.CountOfItems,
    description: 'Count of items',
    length: 8,
    variableLength: true,
  },
  {
    code: AICode.ProductNetWeightKg,
    description: 'Product Net Weight in kg',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductLength1stDimensionM,
    description: 'Product Length/1st Dimension, in meters',
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductWidthDiameter2ndDimensionM,
    description: 'Product Width/Diameter/2nd Dimension,in meters',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductDepthThicknessHeight3rdDimensionM,
    description: 'Product Depth/Thickness/Height/3rd Dimension,in meters',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductAreaSqM,
    description: 'Product Area,in square meters',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductNetVolumeL,
    description: 'Product Net Volume,in liters',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductNetVolumeM,
    description: 'Product Net Volume,in cubic meters',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductNetWeightLbs,
    description: 'Product Net Weight,in pounds',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductLength1stDimensionInch,
    description: 'Product Length/1st Dimension,in inches',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductLength1stDimensionFt,
    description: 'Product Length/1st Dimension,in feet',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductLength1stDimensionYd,
    description: 'Product Length/1st Dimension,in yards',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductWidthDiameter2ndDimensionIn,
    description: 'Product Width/Diameter/2nd Dimension,in inches',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductWidthDiameter2ndDimensionFt,
    description: 'Product Width/Diameter/2nd Dimension,in feet',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductWidthDiameter2ndDimensionYd,
    description: 'Product Width/Diameter/2nd Dimension,in yards',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductDepthThicknessHeight3rdDimensionIn,
    description: 'Product Depth/Thickness/Height/3rd Dimension,in inches',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductDepthThicknessHeight3rdDimensionFt,
    description: 'Product Depth/Thickness/Height/3rd Dimension,in feet',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductDepthThickness3rdDimensionYd,
    description: 'Product Depth/Thickness/3rd Dimension,in yards',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerGrossWeightkg,
    description: 'Container Gross Weight kg',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerLength1stDimensionM,
    description: 'Container Length/1st Dimension Meters',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerWidthDiameter2ndDimensionM,
    description: 'Container Width/Diameter/2nd Dimension Meters',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerDepthThickness3rdDimensionMeters,
    description: 'Container Depth/Thickness/3rdDimension Meters',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerAreaSquareMeters,
    description: 'Container Area Square Meters',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerGrossVolumeL,
    description: 'Container Gross Volume Liters',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerGrossVolumeCubicM,
    description: 'Container Gross Volume CubicMeters',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerGrossWeightLbs,
    description: 'Container Gross Weight Pounds',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerLength1stDimensionIn,
    description: 'Container Length1stDimension in inches',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerLength1stDimensionFt,
    description: 'Container Length/1stDimension,infeet',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerLength1stDimensionYd,
    description: 'Container Length/1stDimensionin,inyards',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerWidthDiameter2ndDimensionIn,
    description: 'Container Width/Diameter/2nd Dimension,in inches',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerWidthDiameter2ndDimensionFt,
    description: 'Container Width/Diameter/2nd Dimension,in feet',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerWidthDiameter2ndDimensionYd,
    description: 'Container Width/Diameter/2nd Dimension,in yards',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerDepthThicknessHeight3rdDimensionIn,
    description: 'Container Depth/Thickness/Height/3rd Dimension,in inches',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerDepthThicknessHeight3rdDimensionFt,
    description: 'Container Depth/Thickness/Height/3rd Dimension,in feet',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerDepthThicknessHeight3rdDimensionY,
    description: 'Container Depth/Thickness/Height/3rd Dimension,in yards',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductAreaSqIn,
    description: 'Product Area SquareInches',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductAreaSqFt,
    description: 'Product Area SquareFeet',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductAreaSqY,
    description: 'Product Area SquareYards',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerAreaSqIn,
    description: 'Container Area SquareInches',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerAreaSqFt,
    description: 'Container Area SquareFeet',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerAreaSqY,
    description: 'Container Area SquareYards',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.NetWeightTroyOz,
    description: 'Net Weight TroyOunces',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.NetWeightVolumeOz,
    description: 'Net Weight/Volume Ounces',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductVolumeQuarts,
    description: 'Product Volume Quarts',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductVolumeGallons,
    description: 'Product Volume Gallons',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerGrossVolumeQuarts,
    description: 'Container Gross Volume Quarts',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerGrossVolumeUSGallons,
    description: 'ContainerGrossVolume U.S.Gallons',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductVolumeCubicInches,
    description: 'ProductVolume CubicInches',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductVolumeCubicFeet,
    description: 'ProductVolume CubicFeet',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ProductVolumeCubicYards,
    description: 'ProductVolume CubicYards',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerGrossVolumeCubicInches,
    description: 'ContainerGrossVolume CubicInches',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerGrossVolumeCubicFeet,
    description: 'ContainerGrossVolume CubicFeet',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.ContainerGrossVolumeCubicYards,
    description: 'ContainerGrossVolume CubicYards',
    fractional: true,
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.NumberofUnitsContained,
    description: 'NumberofUnitsContained',
    length: 8,
    variableLength: true,
  },
  {
    code: AICode.AmountPayableLocalCurrency,
    description: 'Amount payable local currency}',
    fractional: true,
    length: 15,
    variableLength: true,
  },
  {
    code: AICode.AmountPayableISOCurrencyCode,
    description: 'Amount payable with ISO currency code',
    fractional: true,
    length: 18,
    variableLength: true,
  },
  {
    code: AICode.AmountPayablePerSingleItemLocalCurrency,
    description: 'Amount payable per single item local currency',
    fractional: true,
    length: 15,
    variableLength: true,
  },
  {
    code: AICode.AmountPayablePerSingleItemxWithISOcurrencycode,
    description: 'Amount payable persingle itemx with ISO currency code',
    fractional: true,
    length: 18,
    variableLength: true,
  },
  {
    code: AICode.CustomerPurchaseOrderNumber,
    description: 'Customer Purchase Order Number',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.ConsignmentNumber,
    description: 'Consignment Number',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.BillofLadingNumber,
    description: 'BillofLadingnumber',
    length: 17,
    variableLength: false,
  },
  {
    code: AICode.RoutingCode,
    description: 'Routing code',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.ShipToDeliverToLocationCodeGlobalLocationNumber,
    description: 'ShipTo/DeliverToLocationCode GlobalLocationNumber',
    length: 13,
    variableLength: false,
  },
  {
    code: AICode.BillToInvoiceLocationCodeGlobalLocationNumber,
    description: 'BillTo/InvoiceLocationCode GlobalLocationNumber',
    length: 13,
    variableLength: false,
  },
  {
    code: AICode.PurchaseFromLocationCodeGlobalLocationNumber,
    description: 'PurchaseFromLocationCode GlobalLocationNumber',
    length: 13,
    variableLength: false,
  },
  {
    code: AICode.ShipForDeliverForOrForwardToLocationCode,
    description: 'Shipfor,Deliver for,or Forward to Location Code',
    length: 13,
    variableLength: false,
  },
  {
    code: AICode.IdentificationOfAPhysicAllocation,
    description: 'Identification of a physical location',
    length: 13,
    variableLength: false,
  },
  {
    code: AICode.ShipToDeliverToPostalCodeSinglePostalAuthority,
    description: 'ShipTo /DeliverTo PostalCode Single Postal Authority',
    length: 20,
    variableLength: true,
  },
  {
    code: AICode.ShipToDeliverToPostalCodeISOCountryCode,
    description: 'ShipTo / DeliverTo PostalCode ISO CountryCode',
    length: 15,
    variableLength: true,
  },
  {
    code: AICode.CountryofOrigin,
    description: 'Country of Origin',
    length: 3,
    variableLength: false,
  },
  {
    code: AICode.CountryOrCountriesOfInitialProcessing,
    description: 'Country or countries of initial processing',
    length: 15,
    variableLength: true,
  },
  {
    code: AICode.CountryOfProcessing,
    description: 'Country of processing',
    length: 3,
    variableLength: false,
  },
  {
    code: AICode.CountryOfDisassembly,
    description: 'Country of disassembly',
    length: 3,
    variableLength: false,
  },
  {
    code: AICode.CountryOfFullProcessChain,
    description: 'Country of full process chain',
    length: 3,
    variableLength: false,
  },
  {
    code: AICode.NATOStockNumberNSN,
    description: 'NATO Stock Number NSN',
    length: 13,
    variableLength: false,
  },
  {
    code: AICode.UNECEMeatCarcassesAndCutsClassification,
    description: 'UN/ECE Meat Carcasses and cuts classification',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.ExpirationDateAndTime,
    description: 'expiration date and time',
    length: 10,
    variableLength: false,
  },
  {
    code: AICode.ActivePotency,
    description: 'Active Potency',
    length: 4,
    variableLength: true,
  },
  {
    code: AICode.Processorapproval,
    description: 'Processor approval',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.RollProductsWidthLengthCoreDiameterDirectionSplices,
    description: 'Roll Products: Width/Length/CoreDiameter/Direction/Splices',
    length: 14,
    variableLength: false,
  },
  {
    code: AICode.MobilePhoneIdentifier,
    description: 'Mobile phone identifier',
    length: 20,
    variableLength: true,
  },
  {
    code: AICode.GlobalReturnableAssetIdentifier,
    description: 'Global ReturnableAssetIdentifier',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.GlobalIndividualAssetIdentifier,
    description: 'Global IndividualAssetIdentifier',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.PriceperUnitofMeasure,
    description: 'Price perUnitofMeasure',
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.IdentificationOfTheComponentsOfAnItem,
    description: 'identification of the components of an item',
    length: 18,
    variableLength: false,
  },
  {
    code: AICode.InternationalBankAccountNumber,
    description: 'International Bank Account Number',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.DatetimeOfProduction,
    description: 'Date/time of production',
    length: 12,
    variableLength: true,
  },
  {
    code: AICode.GlobalServiceRelationshipNumber,
    description: 'Global ServiceRelationshipNumber',
    length: 18,
    variableLength: false,
  },
  {
    code: AICode.PaymentslipPreferenceNumber,
    description: 'Payment slip preference number',
    length: 25,
    variableLength: true,
  },
  {
    code: AICode.CouponExtendedCodeNumberSystemandOffer,
    description: 'CouponExtendedCode: Number System and Offer',
    length: 6,
    variableLength: false,
  },
  {
    code: AICode.CouponExtendedCodeNumberSystemOfferEndofOffer,
    description: 'CouponExtendedCode: Number System,Offer,End of Offer',
    length: 10,
    variableLength: false,
  },
  {
    code: AICode.CouponExtendedCodeNumberSystemPrecededBy0,
    description: 'CouponExtendedCode: Number System preceded by 0',
    length: 2,
    variableLength: false,
  },
  {
    code: AICode.CouponcodeIDNorthAmerica,
    description: 'CouponcodeID NorthAmerica',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.ExtendedPackagingURL,
    description: 'Extended Packaging URL',
    length: 70,
    variableLength: true,
  },
  {
    code: AICode.MutuallyAgreedBetweenTradingPartners,
    description: 'Mutually Agreed Between Trading Partners',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.InternalCompanyCodes91,
    description: 'Internal Company Codes',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.InternalCompanyCodes92,
    description: 'Internal Company Codes',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.InternalCompanyCodes93,
    description: 'Internal Company Codes',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.InternalCompanyCodes94,
    description: 'Internal Company Codes',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.InternalCompanyCodes95,
    description: 'Internal Company Codes',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.InternalCompanyCodes96,
    description: 'Internal Company Codes',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.InternalCompanyCodes97,
    description: 'Internal Company Codes',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.InternalCompanyCodes98,
    description: 'Internal Company Codes',
    length: 30,
    variableLength: true,
  },
  {
    code: AICode.InternalCompanyCodes99,
    description: 'Internal Company Codes',
    length: 30,
    variableLength: true,
  },
];

export const APPLICATION_IDENTIFIERS: ApplicationIdentifier[] =
  data.map(x => new ApplicationIdentifier(x.code, x.description, x.length, x.variableLength, x.fractional));
